version: "3.5"
services:
  angular-services:
    container_name: angular-crud
    build: ./
    volumes:
      - './:/usr/src/app'
    ports:
      - "4200:80"
    command: >
      bash -c "npm install -c"